/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.icttec.chataplication.main;

import com.icttec.chatapplication.dbmanager.DBManager;
import com.icttec.chatapplication.entity.Users;
import com.icttec.chatapplication.utility.Utility;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author KA VI YA
 */
public class ChatRegister extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ChatRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnsing1 = new rojeru_san.complementos.RSButtonHover();
        btnlog1 = new rojeru_san.complementos.RSButtonHover();
        jButton10 = new javax.swing.JButton();
        edite_profie_pic = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        usertype = new javax.swing.JComboBox<String>();
        email = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        jLabel118 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        cpwd = new javax.swing.JPasswordField();
        pwd = new javax.swing.JPasswordField();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        ShowPassword1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/chat_banner.png"))); // NOI18N
        jLabel16.setText("jLabel4");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 540, 470));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Chat Application");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("Connect with others");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 10));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/chat_app_icon.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 100));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Wellcome!!");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Create Your Account");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/icons8_Forgot_Password_50px_4.png"))); // NOI18N
        jLabel22.setText("Forgot Password?");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 180, 50));

        btnsing1.setBackground(new java.awt.Color(255, 153, 0));
        btnsing1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnsing1.setText("Sing Up");
        btnsing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsing1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 150, 40));

        btnlog1.setBackground(new java.awt.Color(204, 0, 0));
        btnlog1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnlog1.setText("Login");
        btnlog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlog1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnlog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 150, 40));

        jButton10.setBackground(new java.awt.Color(0, 204, 204));
        jButton10.setText("add image");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 90, -1));

        edite_profie_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/user1.png"))); // NOI18N
        edite_profie_pic.setText("jLabel31");
        jPanel4.add(edite_profie_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 140, 120));

        jLabel128.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel128.setForeground(new java.awt.Color(255, 255, 255));
        jLabel128.setText("Full Name");
        jPanel4.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 32));

        jLabel115.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(255, 255, 255));
        jLabel115.setText("Email");
        jPanel4.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, 29));

        jLabel116.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(255, 255, 255));
        jLabel116.setText("User Type");
        jPanel4.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 32));

        usertype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User", "Admin" }));
        usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertypeActionPerformed(evt);
            }
        });
        jPanel4.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 210, 28));
        jPanel4.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 210, 32));
        jPanel4.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 210, 29));
        jPanel4.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 210, 29));

        jLabel118.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(255, 255, 255));
        jLabel118.setText("User Name");
        jPanel4.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 32));

        jPanel20.setBackground(new java.awt.Color(0, 153, 204));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel123.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(255, 255, 255));
        jLabel123.setText("Once Set the password Cann't Modifiey");
        jPanel20.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        cpwd.setText("jPassw");
        jPanel20.add(cpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, 181, 30));

        pwd.setText("jPas1");
        jPanel20.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 181, 30));

        jLabel124.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(255, 255, 255));
        jLabel124.setText("Re-enter the Password");
        jPanel20.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        jLabel125.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(255, 255, 255));
        jLabel125.setText("Password");
        jPanel20.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        ShowPassword1.setBackground(new java.awt.Color(0, 204, 204));
        ShowPassword1.setForeground(new java.awt.Color(255, 255, 255));
        ShowPassword1.setText(" Show Password");
        ShowPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPassword1MouseClicked(evt);
            }
        });
        jPanel20.add(ShowPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jPanel4.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){    
                System.exit(0);
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void btnsing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsing1ActionPerformed
         byte[] image = null;

        ImageIcon avatar = (ImageIcon) edite_profie_pic.getIcon();
        if (avatar != null) {
            Utility utility = new Utility();
            try {

                BufferedImage bImage = utility.ImageIconToBufferedImage(avatar);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                ImageIO.write(bImage, "png", bos);
                image = bos.toByteArray();

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"Error: "+ex.getMessage());
            }

        }

        Users addusers = new Users();
       // addusers.setId(getAdmin().getId());
        addusers.setEmail(email.getText().trim());
        addusers.setUsername(uname.getText().trim());
        addusers.setNickname(fname.getText().trim());
        addusers.setPassword(pwd.getText().trim());
        addusers.setProfileImage(image);
        addusers.setUserType("User");

        String cpassword = cpwd.getText().trim();

        DBManager dbManager = new DBManager();
        if((email.getText().equals("")||uname.getText().equals("")||fname.getText().equals("")||pwd.getText().equals("")||cpwd.getText().equals(""))){
            JOptionPane.showMessageDialog(this,"please fill al the fields!!");
        }else{
            if(pwd.getText().equalsIgnoreCase(cpassword)){
                if (dbManager.AddUser(addusers)) {
                    JOptionPane.showMessageDialog(this,"Account Create successfully..");
                    ChatLogin chatLogin = new ChatLogin();
                    chatLogin.setVisible(true);
        this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this,"Account can not create!");
                }
            }else{
                JOptionPane.showMessageDialog(this,"password not match!");
            }
        }

        //        img_profile2.setIcon(avatar);
        //        img_profile2.setIcon(avatar);
    }//GEN-LAST:event_btnsing1ActionPerformed

    private void btnlog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlog1ActionPerformed
        ChatLogin chatLogin = new ChatLogin();
        chatLogin.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnlog1ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked

        JFileChooser chooser = new JFileChooser(); //open image file file
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG Images", "jpg", "png"); //set image type filter
        chooser.setFileFilter(filter); //filter
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) { //if image selected
            File file = chooser.getSelectedFile(); //get selected file
            String strfilepath = file.getAbsolutePath(); //get abs path

            try {
                ImageIcon icon = new ImageIcon(strfilepath); //string image path open as a image icon
                ImageIcon iconresized = new ImageIcon(icon.getImage().getScaledInstance(120, 120, Image.SCALE_DEFAULT)); //resize image icon fit for profile icon label
                edite_profie_pic.setText(null); // remove label text
                edite_profie_pic.setIcon(iconresized); //set seleted image to profile icon label

            } catch (Exception e) {
                System.out.println("Exception occurred : " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void usertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertypeActionPerformed

    private void ShowPassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPassword1MouseClicked
        if(ShowPassword1.isSelected()){
            pwd.setEchoChar((char)0);
            cpwd.setEchoChar((char)0);
            ShowPassword1.setText("Hide Password");
        }
        else{
            pwd.setEchoChar('•');
            cpwd.setEchoChar('•');
            ShowPassword1.setText("Show Password");
        }
    }//GEN-LAST:event_ShowPassword1MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ShowPassword1;
    private rojeru_san.complementos.RSButtonHover btnlog1;
    private rojeru_san.complementos.RSButtonHover btnsing1;
    private javax.swing.JPasswordField cpwd;
    private javax.swing.JLabel edite_profie_pic;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField uname;
    private javax.swing.JComboBox<String> usertype;
    // End of variables declaration//GEN-END:variables
}
