package com.icttec.chatapplication.entity;
// Generated Mar 1, 2023 2:01:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private int status;
     private Date createdDate;
     private Date createdTime;
     private int isDeleted;

    public Groups() {
    }

	
    public Groups(String name, String description, int status, int isDeleted) {
        this.name = name;
        this.description = description;
        this.status = status;
        this.isDeleted = isDeleted;
    }
    public Groups(String name, String description, int status, Date createdDate, Date createdTime, int isDeleted) {
       this.name = name;
       this.description = description;
       this.status = status;
       this.createdDate = createdDate;
       this.createdTime = createdTime;
       this.isDeleted = isDeleted;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int isStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


